# Site settings
title: LCA  
email: lowrycory23@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a family private school! We are not open to the public!!!
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://LCA.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown